package by.jwd.finaltaskweb.controller;

public enum CommandEnum {

	READALLSCHEDULE, READALLTEACHER, READALLMEMBERSHIPTYPES, READALLCLIENT, LOGINATION, REGISTRATION, LOGOUT,
	UPDATECLIENT, UPDATEPASSWORD, PLANNEDVISITS, MYVALIDMEMBERSHIPS, MYMEMBERSHIPSPERIOD, CREATEMEMBERSHIP, MYVISITS,
	CANCELVISIT, READGROUPBYSCHEDULE, READGROUPBYSTYLE, READGROUPBYLEVEL, READPLANNEDCLASSESBYGROUP, CREATEVISIT,
	READALLSTYLE, READALLWEEKDAY, READALLLEVEL, READAVAILIABLEDATESBYGROUP, READALLAVAILIABLEDATES, WRONGCOMMAND
}