package by.jwd.finaltaskweb.controller;

public enum CommandEnum {

	READALLSCHEDULE, READALLTEACHER, READALLMEMBERSHIPTYPES, READALLCLIENT, LOGINATION, REGISTRATION, LOGOUT,
	UPDATECLIENT, UPDATEPASSWORD, PLANNEDVISITS, MYVALIDMEMBERSHIPS, CHOOSEMEMBERSHIP, MYMEMBERSHIPSPERIOD,
	CREATEMEMBERSHIP, MYVISITS, CANCELVISIT, READGROUPBYSCHEDULE, READGROUPBYSTYLE, READGROUPBYLEVEL, READGROUPBYDATE,
	READPLANNEDCLASSESBYGROUP, CONFIRMVISIT, CREATEVISIT, READALLSTYLE, READALLWEEKDAY, READALLLEVEL,
	READAVAILIABLEDATESBYGROUP, READALLAVAILIABLEDATES, READPLANNEDCLASSESBYTEACHER, MARKPRESENCE, CANCELMARKEDPRESENCE,
	READVISITSBYGROUPANDDATE, READGROUPSBYTEACHER, READVISITCOUNTBYTEACHERGROUPSANDPERIOD, WRONGCOMMAND
}